---
version: "2.1"
services:
  nextcloud:
    image: ghcr.io/linuxserver/nextcloud
    container_name: nextcloud
    networks:
        - cloudnet
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Europe/Berlin
    volumes:
      - ./appdata:/config
      - ./data:/data
    ports:
      - 8080:80
      - 8443:443
    restart: unless-stopped
    logging:
      # limit logs retained on host to 25MB
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "50"
  confluencedb:
    container_name: confluencedb
    image: postgres:11-alpine
    networks:
      - cloudnet
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      - 'POSTGRES_USER=cloud'
      - 'POSTGRES_DB=clouddb'
      # CHANGE THE PASSWORD!
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_ENCODING=UTF8'
      - 'POSTGRES_COLLATE=C'
      - 'POSTGRES_COLLATE_TYPE=C'
    restart: unless-stopped
    logging:
      # limit logs retained on host to 25MB
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "50"
networks:
  cloudnet:
    driver: bridge