version: "3"
services:
  app:
    image: knelldev/tekbase:latest
    restart: always
    ports:
      # Public HTTP Port:
      - 80:80
      # Public HTTPS Port:
      - 443:443
    volumes:
      # - ./config.json:/app/config/production.json
    depends_on:
      - db
  db:
    image: mariadb
    restart: always
    environment:
      # CHANGE THE PASSWORD!
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "npm"
      MYSQL_USER: "npm"
      # CHANGE THE PASSWORD!
      MYSQL_PASSWORD: "password"
    volumes:
      - ./data/mysql:/var/lib/mysql
